### PR TITLE
for swift2.1

### PR DESCRIPTION
**Pull request by wddwycc**

### CODE REVIEW

**Comment by remirobert** [comment]
Thanks for you contribution

is there a problem with your PR, or you just wanted to erase the project ?

**Comment by wddwycc** [comment]
I replaced the file by mistake....

**Comment by remirobert** [comment]
I am sorry but I don't see any addition, or update in your PR. Maybe to close and re open a new one ?

Thanks in advance

**Comment by wddwycc** [comment]
close it...

**Pull request closed without merging**
